// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjijlhihwafioolrtjrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqaWpsaGlod2FmaW9vbHJ0anJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTgwMjAsImV4cCI6MjA2MzM5NDAyMH0.iKauccl_V08Sfh3zkToTc0AkWWJ-iulCBg-Gi3O_ZpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);